CREATE INDEX category_idx ON products USING btree (category_id);
CREATE INDEX feature_name_idx ON feature_values USING btree (feature_name_id);
CREATE INDEX pfj_product_idx ON product_feature_join USING btree (product_id);
CREATE INDEX pfj_feature_value_idx ON product_feature_join USING btree (feature_value_id);
CREATE INDEX related1_product_idx ON related_products USING btree (product_id);
CREATE INDEX related2_product_idx ON related_products USING btree (related_product_id);
CREATE INDEX styles_product_idx ON styles USING btree (product_id);
CREATE INDEX sku_style_idx ON skus USING btree (style_id);
CREATE INDEX sku_size_idx ON skus USING btree (size_id);
CREATE INDEX photo_style_idx ON photos USING btree (style_id);
CREATE INDEX user_session_idx ON carts USING btree (user_session);
-- DROP INDEX category_idx;
-- DROP INDEX feature_name_idx;
-- DROP INDEX pfj_product_idx;
-- DROP INDEX pfj_feature_value_idx;
-- DROP INDEX related1_product_idx;
-- DROP INDEX related2_product_idx;
-- DROP INDEX styles_product_idx;
-- DROP INDEX sku_style_idx;
-- DROP INDEX sku_size_idx;
-- DROP INDEX photo_style_idx;
-- DROP INDEX user_session_idx;